### ISSUE TITLE
Docker Compose Runs servers in production mode.

### ISSUE THREAD

**Issue by My5z0n** [TPiechocki/ServerRoomMonitoringApp#13]
After running developer docker, compose server seems to take settings from appsettings.json, not from appsettings.Developer.json. 
It is possible to change that @TPiechocki. I need this to distinguish production database and development database

**Comment by TPiechocki** [comment]
Yes, it's possible and I should have done it initially.

Section like that for each service in docker compose should do the job:
```
services:
  webapplication1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
```
